---
- name: Create config directory
  file:
    path: '{{ item }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    state: directory
    mode: '0775'
    recurse: true
  with_items:
    - '{{ lez_service_conf }}'
    - '{{ lez_sequencer_vol }}'
    - '{{ lez_indexer_cont_vol }}'
    - '{{ lez_blockchain_config_path | dirname }}'
    - '{{ lez_indexer_config_path | dirname }}'
    - '{{ lez_sequencer_config_path | dirname }}'

- name: Create sequencer config
  register: lez_sequencer_config_file
  template:
    src: 'config.json.j2'
    dest: '{{ lez_sequencer_config_path }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    mode: '0660'
  vars:
    lez_config_content: '{{ lez_sequencer_config }}'

- name: Create indexer config
  register: lez_indexer_config_file
  template:
    src: 'config.json.j2'
    dest: '{{ lez_indexer_config_path }}'
    owner: '{{ lez_host_uid }}'
    group: dockremap
    mode: '0660'
  vars:
    lez_config_content: '{{ lez_indexer_config }}'

- name: Check blockchain config
  register: lez_blockchain_config_file
  stat:
    path: '{{ lez_blockchain_config_path }}'
