---
lez_domain: '{{ stage }}net.lez.logos.co'
lez_service_name: 'logos-exec-zone-{{ stage }}net'
lez_explorer_cont_port: 8081
lez_blockchain_cont_api_port: 8080
lez_blockchain_cont_swarm_port: 3000
lez_sequencer_config: '{{ lookup("ansible.builtin.file", "../files/lez/"+stage+"/sequencer_config.json") | mandatory }}'
lez_indexer_config:   '{{ lookup("ansible.builtin.file", "../files/lez/"+stage+"/indexer_config.json") | mandatory }}'
# FIXME: Unknown reason why we can't use logos_node_blockchain_initial_peers_env[stage].
lez_blockchain_initial_peers:
  - '/ip4/65.108.203.235/udp/3000/quic-v1/p2p/12D3KooWNbZTQ86TZ9MrZ2wm6iUFFj25AFTzFLUD7i6XkZHoUzU8'
  - '/ip4/65.108.203.235/udp/3001/quic-v1/p2p/12D3KooWNhXaH4XTX6Pp66NDQZxZpXYQzeruwwraMvTxojz1QXPJ'
  - '/ip4/65.108.203.235/udp/3002/quic-v1/p2p/12D3KooWNTLPg5uYPKgZCDvzyaWNwZNcwVKmfS2bNv52E9L9P7Hf'
  - '/ip4/65.108.203.235/udp/50001/quic-v1/p2p/12D3KooWMULUG8RXC2esnfLcVzGHohf6KNPSswkCKa1mdpXz4tHH'

# Certbot
certbot_docker_enabled: true
certbot_admin_email: 'devops@status.im'
certbot_services_to_stop: ['nginx']
certbot_certs:
  - domains:
      - '{{ lez_domain }}'

# Nginx
nginx_sites:
  chat_kc_https:
    - listen 443 ssl
    - server_name {{ lez_domain }}

    - ssl_certificate     /etc/letsencrypt/live/{{ lez_domain }}/fullchain.pem
    - ssl_certificate_key /etc/letsencrypt/live/{{ lez_domain }}/privkey.pem

    - location / {
        proxy_pass http://localhost:{{ lez_explorer_cont_port }}/;
      }

# Firewall
open_ports_list:
  nginx:
    - { port: [80, 443], proto: 'tcp', comment: 'Nginx' }
  logos-blockchain:
    - { port: '{{ lez_blockchain_cont_swarm_port }}', proto: tcp, comment: 'Logos Blockchain Swarm' }
